let map = new Map()
map.set(1,'one')
map.set(2,'two')
map.set('alpha',15)
map.set('b-8',20)
console.log(map)
let two = map.get(2)
console.log(map.get(1))
console.log(two)
let size = map.size
console.log(size)

let myMap = new Map()
myMap.set(1,'one')
myMap.set(2,'two')
myMap.set(3,'three')
myMap.set(4,'four')
console.log(myMap)

console.log(map.has(1))
console.log(map.has(3))
map.delete(1)
console.log(map)
map.clear()
console.log(map)

console.log(myMap.entries())
console.log(myMap.keys())
console.log(myMap.values())
